### ISSUE TITLE
ValueError in runScript is raised but never caught

### ISSUE THREAD

**Issue by fennesz** [AllToTheX/RemotePython#10]
Unfortunately, I found this while expanding the unittests. The following expection (Line 128 in RemotePython.py) is never caught:
```
        except ValueError:
            print "Could not copy the script"
            raise
```
When the ValueError is raised in code, the function immediately returns so print is never called.

**Comment by AllToTheX** [comment]
Could you post the steps to reproduce and the error message?

**Comment by fennesz** [comment]
Thanks, I guess I have something to learn about raising issues in a proper way. :)

Run the following:

```
obj = RemotePython()
obj.runScript()
```

It should print out: "Could not copy the script", but it doesn't.

**Comment by AllToTheX** [comment]
if you run that it should raise ValueError("A script should be specified in either the object or the function call") on line 115.

It should print the "could not copy the script" if there is a script specified but it for some reason failed to copy it to the target, might be because the connection is bad or the scp was denied. There is an issue in __copyScript() as it catches ALL exceptions, not just the CalledProcessError. and it never raises ValueError so you are right, it will pass right through if that situation occurs.

**Comment by AllToTheX** [comment]
Fixed it by catching CalledProcessError in copyScript and removed the ValueError catch in runScript

**Comment by fennesz** [comment]
Great! Love the skiptest condition by the way.
